import type { Product, Promotion, User, Brand } from './types';

export const products: Omit<Product, 'status'>[] = [
  {
    id: 1,
    name: 'Modern Smartphone',
    category: 'Electronics',
    categories: { main: 'Electronics', sub: 'Mobiles & Accessories', type: 'Smartphones', gender: 'Unisex', ageGroup: 'Adult' },
    price: 649.99,
    originalPrice: 699.99,
    brand: 'TechCorp',
    description: 'A sleek and powerful smartphone with a stunning display and all-day battery life.',
    imageUrl: 'https://picsum.photos/seed/smartphone/600/600',
    images: ['https://picsum.photos/seed/smartphone/600/600', 'https://picsum.photos/seed/smartphone2/600/600', 'https://picsum.photos/seed/smartphone3/600/600'],
    rating: 4.5,
    reviews: [
        { userId: 'customer-user', userName: 'Customer User', rating: 5, comment: 'Absolutely love this phone! The camera is amazing.', date: new Date(Date.now() - 86400000 * 2).toISOString() },
        { userId: 'seller-user', userName: 'Seller User', rating: 4, comment: 'Great value for the price. A bit slippery though.', date: new Date(Date.now() - 86400000 * 5).toISOString() },
    ],
    stock: 50,
    sellerId: 'seller-user',
    specifications: {
      'Display': '6.7" Super Retina XDR',
      'Processor': 'A16 Bionic Chip',
      'Camera': '48MP Main, 12MP Ultra Wide',
      'Battery': 'Up to 29 hours video playback',
      'Storage': '256GB',
      'Operating System': 'iOS 17'
    },
  },
  {
    id: 2,
    name: 'Wireless Noise-Cancelling Headphones',
    category: 'Electronics',
    categories: { main: 'Electronics', sub: 'Audio', type: 'Headphones', gender: 'Unisex', ageGroup: 'Adult' },
    price: 249.99,
    brand: 'AudioPhile',
    description: 'Immerse yourself in music with these high-fidelity wireless headphones.',
    imageUrl: 'https://picsum.photos/seed/headphones/400/400',
    images: ['https://picsum.photos/seed/headphones/600/600', 'https://picsum.photos/seed/headphones2/600/600'],
    rating: 4.8,
    reviews: [
        { userId: 'customer-user', userName: 'Customer User', rating: 5, comment: 'Best headphones I have ever owned. The noise cancelling is top-notch.', date: new Date(Date.now() - 86400000 * 3).toISOString() },
    ],
    stock: 75,
  },
  {
    id: 3,
    name: 'Classic Leather Jacket',
    category: 'Fashion',
    categories: { main: 'Fashion', sub: 'Men\'s Apparel', type: 'Jackets', gender: 'Men', ageGroup: 'Adult' },
    price: 199.99,
    brand: 'StyleStitch',
    description: 'A timeless leather jacket that adds a cool edge to any outfit.',
    imageUrl: 'https://picsum.photos/seed/jacket/400/400',
    images: ['https://picsum.photos/seed/jacket/600/600', 'https://picsum.photos/seed/jacket2/600/600'],
    rating: 4.7,
    reviews: [],
    stock: 30,
    sellerId: 'seller-user',
  },
  {
    id: 4,
    name: 'Comfortable Running Shoes',
    category: 'Fashion',
    categories: { main: 'Fashion', sub: 'Footwear', type: 'Sports Shoes', gender: 'Unisex', ageGroup: 'Adult' },
    price: 129.99,
    brand: 'RunFast',
    description: 'Lightweight and supportive running shoes for your daily workout.',
    imageUrl: 'https://picsum.photos/seed/shoes/400/400',
    images: ['https://picsum.photos/seed/shoes/600/600', 'https://picsum.photos/seed/shoes2/600/600', 'https://picsum.photos/seed/shoes3/600/600'],
    rating: 4.6,
    reviews: [],
    stock: 100,
  },
  {
    id: 5,
    name: 'The Art of Programming',
    category: 'Books',
    categories: { main: 'Books', sub: 'Computers & Tech', type: 'Programming', ageGroup: 'Adult' },
    price: 49.99,
    brand: 'CodePress',
    description: 'A comprehensive guide to mastering the fundamentals of computer programming.',
    imageUrl: 'https://picsum.photos/seed/book1/400/400',
    images: ['https://picsum.photos/seed/book1/600/600'],
    rating: 4.9,
    reviews: [],
    stock: 120,
  },
  {
    id: 6,
    name: 'Sci-Fi Epic: "Galaxy\'s Edge"',
    category: 'Books',
    categories: { main: 'Books', sub: 'Science Fiction & Fantasy', type: 'Space Opera', ageGroup: 'Adult' },
    price: 19.99,
    originalPrice: 24.99,
    brand: 'PubHouse',
    description: 'An epic space opera adventure that will keep you on the edge of your seat.',
    imageUrl: 'https://picsum.photos/seed/book2/400/400',
    images: ['https://picsum.photos/seed/book2/600/600'],
    rating: 4.4,
    reviews: [],
    stock: 200,
  },
  {
    id: 7,
    name: 'Organic Avocado Box (6 ct.)',
    category: 'Groceries',
    categories: { main: 'Groceries', sub: 'Fresh Produce', type: 'Fruits' },
    price: 12.99,
    brand: 'FreshFarms',
    description: 'Creamy and delicious organic avocados, perfect for toast, salads, and guacamole.',
    imageUrl: 'https://picsum.photos/seed/avocado/400/400',
    images: ['https://picsum.photos/seed/avocado/600/600'],
    rating: 4.8,
    reviews: [],
    stock: 80,
  },
  {
    id: 8,
    name: 'Artisanal Sourdough Bread',
    category: 'Groceries',
    categories: { main: 'Groceries', sub: 'Bakery', type: 'Bread' },
    price: 7.99,
    brand: 'Bakery Co.',
    description: 'A freshly baked loaf of artisanal sourdough bread with a perfect crust.',
    imageUrl: 'https://picsum.photos/seed/bread/400/400',
    images: ['https://picsum.photos/seed/bread/600/600'],
    rating: 4.9,
    reviews: [],
    stock: 60,
  },
  {
    id: 9,
    name: 'Minimalist Coffee Maker',
    category: 'Home & Kitchen',
    categories: { main: 'Home & Kitchen', sub: 'Kitchen Appliances', type: 'Coffee Makers', gender: 'Unisex', ageGroup: 'Adult' },
    price: 89.99,
    brand: 'HomeBrew',
    description: 'Brew the perfect cup of coffee with this elegant and easy-to-use coffee maker.',
    imageUrl: 'https://picsum.photos/seed/coffee/400/400',
    images: ['https://picsum.photos/seed/coffee/600/600', 'https://picsum.photos/seed/coffee2/600/600'],
    rating: 4.5,
    reviews: [],
    stock: 45,
    sellerId: 'seller-user',
  },
  {
    id: 10,
    name: 'Stainless Steel Cookware Set',
    category: 'Home & Kitchen',
    categories: { main: 'Home & Kitchen', sub: 'Cookware', type: 'Sets', gender: 'Unisex', ageGroup: 'Adult' },
    price: 299.99,
    brand: 'ChefPro',
    description: 'A complete set of high-quality stainless steel pots and pans for all your cooking needs.',
    imageUrl: 'https://picsum.photos/seed/cookware/400/400',
    images: ['https://picsum.photos/seed/cookware/600/600', 'https://picsum.photos/seed/cookware2/600/600'],
    rating: 4.7,
    reviews: [],
    stock: 25,
  },
   {
    id: 11,
    name: 'Smart Laptop Pro',
    category: 'Electronics',
    categories: { main: 'Electronics', sub: 'Computers', type: 'Laptops', gender: 'Unisex', ageGroup: 'Adult' },
    price: 1299.00,
    brand: 'TechCorp',
    description: 'Ultra-thin, powerful laptop for professionals on the go.',
    imageUrl: 'https://picsum.photos/seed/laptop/400/400',
    images: ['https://picsum.photos/seed/laptop/600/600', 'https://picsum.photos/seed/laptop2/600/600', 'https://picsum.photos/seed/laptop3/600/600'],
    rating: 4.9,
    reviews: [],
    stock: 40,
  },
  {
    id: 12,
    name: 'Designer Denim Jeans',
    category: 'Fashion',
    categories: { main: 'Fashion', sub: 'Men\'s Apparel', type: 'Jeans', gender: 'Men', ageGroup: 'Adult' },
    price: 89.50,
    brand: 'StyleStitch',
    description: 'Perfectly fitting denim jeans for a stylish, casual look.',
    imageUrl: 'https://picsum.photos/seed/jeans/400/400',
    images: ['https://picsum.photos/seed/jeans/600/600', 'https://picsum.photos/seed/jeans2/600/600'],
    rating: 4.3,
    reviews: [],
    stock: 90,
    sellerId: 'seller-user',
  },
];

export const promotions: Promotion[] = [
    {
        id: 'promo1',
        title: 'End of Season Sale',
        subtitle: 'Get up to 50% off on selected fashion items. Limited time offer!',
        imageUrl: 'https://picsum.photos/seed/salebanner/1200/600',
        link: '/products?category=Fashion'
    },
    {
        id: 'promo2',
        title: 'New Electronics Arrived',
        subtitle: 'Discover the latest in tech. Powerful, sleek, and ready for you.',
        imageUrl: 'https://picsum.photos/seed/techbanner/1200/600',
        link: '/products?category=Electronics'
    },
    {
        id: 'promo3',
        title: 'Cozy Home Essentials',
        subtitle: 'Everything you need to make your space comfortable and stylish.',
        imageUrl: 'https://picsum.photos/seed/homebanner/1200/600',
        link: '/products?category=Home%20&%20Kitchen'
    }
];

export const brands: Brand[] = [
    { name: 'TechCorp', logoUrl: 'https://picsum.photos/seed/techcorplogo/200/100?grayscale', link: '/products?brand=TechCorp' },
    { name: 'AudioPhile', logoUrl: 'https://picsum.photos/seed/audiophilelogo/200/100?grayscale', link: '/products?brand=AudioPhile' },
    { name: 'StyleStitch', logoUrl: 'https://picsum.photos/seed/stylestitchlogo/200/100?grayscale', link: '/products?brand=StyleStitch' },
    { name: 'RunFast', logoUrl: 'https://picsum.photos/seed/runfastlogo/200/100?grayscale', link: '/products?brand=RunFast' },
    { name: 'HomeBrew', logoUrl: 'https://picsum.photos/seed/homebrewlogo/200/100?grayscale', link: '/products?brand=HomeBrew' },
    { name: 'ChefPro', logoUrl: 'https://picsum.photos/seed/chefprologo/200/100?grayscale', link: '/products?brand=ChefPro' },
];